name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - next-sdks
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          ls
          python -m pip install --upgrade pip
          pip install -r en/asgardeo/requirements.txt

      - name: Setup caching
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Build MkDocs Documentation
        run: |
          cd en/asgardeo
          mkdocs build
          cd ../../
          
      - name: ⚙️ Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v3

      - name: 🌩 Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: en/asgardeo/site

      - name: 🔥 Deploy to GitHub Pages
        id: deploy-gh-pages
        uses: actions/deploy-pages@v4
